// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class LobbyPlayer {
    [DataMember(Name = "Id")]
    public ulong Id;
    [DataMember(Name = "LobbyId")]
    public ulong LobbyId;
    [DataMember(Name = "PlayerId")]
    public SpacetimeDB.Identity PlayerId;
    [DataMember(Name = "Tribe")]
    public uint Tribe;

    public LobbyPlayer(
        ulong Id,
        ulong LobbyId,
        SpacetimeDB.Identity PlayerId,
        uint Tribe
    ) {
      this.Id = Id;
      this.LobbyId = LobbyId;
      this.PlayerId = PlayerId;
      this.Tribe = Tribe;
    }

    public LobbyPlayer() {
    }
  }
}
