// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class Lobby {
    [DataMember(Name = "Id")]
    public ulong Id;
    [DataMember(Name = "MaxPlayers")]
    public uint MaxPlayers;
    [DataMember(Name = "Players")]
    public uint Players;
    [DataMember(Name = "Ready")]
    public uint Ready;
    [DataMember(Name = "Started")]
    public bool Started;
    [DataMember(Name = "Starting")]
    public bool Starting;

    public Lobby(
        ulong Id,
        uint MaxPlayers,
        uint Players,
        uint Ready,
        bool Started,
        bool Starting
    ) {
      this.Id = Id;
      this.MaxPlayers = MaxPlayers;
      this.Players = Players;
      this.Ready = Ready;
      this.Started = Started;
      this.Starting = Starting;
    }

    public Lobby() {
    }
  }
}
