// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  [SpacetimeDB.Type]
  [DataContract]
  public sealed partial class StartLobbySchedule {
    [DataMember(Name = "Id")]
    public ulong Id;
    [DataMember(Name = "ScheduledAt")]
    public SpacetimeDB.ScheduleAt ScheduledAt;

    public StartLobbySchedule(
        ulong Id,
        SpacetimeDB.ScheduleAt ScheduledAt
    ) {
      this.Id = Id;
      this.ScheduledAt = ScheduledAt;
    }

    public StartLobbySchedule() {
      this.ScheduledAt = null!;
    }
  }
}
