<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNext.Threading" Version="6.6.5"/>
    <PackageReference Include="GodotSharp" Version="4.7.2"/>
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <None Remove="resources\troops.json"/>
    <EmbeddedResource Include="resources\troops.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <None Remove="resources\tribes.json"/>
    <EmbeddedResource Include="resources\tribes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <None Remove="resources\tech_tree.json"/>
    <EmbeddedResource Include="resources\tech_tree.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
