// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class LobbyPlayerHandle : RemoteTableHandle<EventContext, LobbyPlayer> {
      protected override string RemoteTableName => "LobbyPlayer";

      public sealed class IdUniqueIndex : UniqueIndexBase<ulong> {
        protected override ulong GetKey(LobbyPlayer row) => row.Id;

        public IdUniqueIndex(LobbyPlayerHandle table) : base(table) { }
      }

      public readonly IdUniqueIndex Id;

      public sealed class LobbyAndPlayerIndex : BTreeIndexBase<(ulong LobbyId, SpacetimeDB.Identity PlayerId)> {
        protected override (ulong LobbyId, SpacetimeDB.Identity PlayerId) GetKey(LobbyPlayer row) => (row.LobbyId, row.PlayerId);

        public LobbyAndPlayerIndex(LobbyPlayerHandle table) : base(table) { }
      }

      public readonly LobbyAndPlayerIndex LobbyAndPlayer;

      internal LobbyPlayerHandle(DbConnection conn) : base(conn) {
        Id = new(this);
        LobbyAndPlayer = new(this);
      }

      protected override object GetPrimaryKey(LobbyPlayer row) => row.Id;
    }

    public readonly LobbyPlayerHandle LobbyPlayer;
  }
}
