// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class LobbyHandle : RemoteTableHandle<EventContext, Lobby> {
      protected override string RemoteTableName => "Lobby";

      public sealed class IdUniqueIndex : UniqueIndexBase<ulong> {
        protected override ulong GetKey(Lobby row) => row.Id;

        public IdUniqueIndex(LobbyHandle table) : base(table) { }
      }

      public readonly IdUniqueIndex Id;

      internal LobbyHandle(DbConnection conn) : base(conn) {
        Id = new(this);
      }

      protected override object GetPrimaryKey(Lobby row) => row.Id;
    }

    public readonly LobbyHandle Lobby;
  }
}
