// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteTables {
    public sealed class StartLobbyScheduleHandle : RemoteTableHandle<EventContext, StartLobbySchedule> {
      protected override string RemoteTableName => "StartLobbySchedule";

      public sealed class IdUniqueIndex : UniqueIndexBase<ulong> {
        protected override ulong GetKey(StartLobbySchedule row) => row.Id;

        public IdUniqueIndex(StartLobbyScheduleHandle table) : base(table) { }
      }

      public readonly IdUniqueIndex Id;

      internal StartLobbyScheduleHandle(DbConnection conn) : base(conn) {
        Id = new(this);
      }

      protected override object GetPrimaryKey(StartLobbySchedule row) => row.Id;
    }

    public readonly StartLobbyScheduleHandle StartLobbySchedule;
  }
}
