// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void AddReadyHandler(ReducerEventContext ctx, ulong lobbyId);
    public event AddReadyHandler? OnAddReady;

    public void AddReady(ulong lobbyId) {
      conn.InternalCallReducer(new Reducer.AddReady(lobbyId), this.SetCallReducerFlags.AddReadyFlags);
    }

    public bool InvokeAddReady(ReducerEventContext ctx, Reducer.AddReady args) {
      if (OnAddReady == null)
        return false;
      OnAddReady(
          ctx,
          args.LobbyId
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AddReady : Reducer, IReducerArgs {
      [DataMember(Name = "lobbyId")]
      public ulong LobbyId;

      public AddReady(ulong LobbyId) {
        this.LobbyId = LobbyId;
      }

      public AddReady() {
      }

      string IReducerArgs.ReducerName => "AddReady";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags AddReadyFlags;
    public void AddReady(CallReducerFlags flags) => AddReadyFlags = flags;
  }
}
