// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void CreateLobbyHandler(ReducerEventContext ctx, uint maxPlayers, uint tribe);
    public event CreateLobbyHandler? OnCreateLobby;

    public void CreateLobby(uint maxPlayers, uint tribe) {
      conn.InternalCallReducer(new Reducer.CreateLobby(maxPlayers, tribe), this.SetCallReducerFlags.CreateLobbyFlags);
    }

    public bool InvokeCreateLobby(ReducerEventContext ctx, Reducer.CreateLobby args) {
      if (OnCreateLobby == null)
        return false;
      OnCreateLobby(
          ctx,
          args.MaxPlayers,
          args.Tribe
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CreateLobby : Reducer, IReducerArgs {
      [DataMember(Name = "maxPlayers")]
      public uint MaxPlayers;
      [DataMember(Name = "tribe")]
      public uint Tribe;

      public CreateLobby(
          uint MaxPlayers,
          uint Tribe
      ) {
        this.MaxPlayers = MaxPlayers;
        this.Tribe = Tribe;
      }

      public CreateLobby() {
      }

      string IReducerArgs.ReducerName => "CreateLobby";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags CreateLobbyFlags;
    public void CreateLobby(CallReducerFlags flags) => CreateLobbyFlags = flags;
  }
}
