// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void JoinLobbyHandler(ReducerEventContext ctx, ulong lobbyId, uint tribe);
    public event JoinLobbyHandler? OnJoinLobby;

    public void JoinLobby(ulong lobbyId, uint tribe) {
      conn.InternalCallReducer(new Reducer.JoinLobby(lobbyId, tribe), this.SetCallReducerFlags.JoinLobbyFlags);
    }

    public bool InvokeJoinLobby(ReducerEventContext ctx, Reducer.JoinLobby args) {
      if (OnJoinLobby == null)
        return false;
      OnJoinLobby(
          ctx,
          args.LobbyId,
          args.Tribe
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JoinLobby : Reducer, IReducerArgs {
      [DataMember(Name = "lobbyId")]
      public ulong LobbyId;
      [DataMember(Name = "tribe")]
      public uint Tribe;

      public JoinLobby(
          ulong LobbyId,
          uint Tribe
      ) {
        this.LobbyId = LobbyId;
        this.Tribe = Tribe;
      }

      public JoinLobby() {
      }

      string IReducerArgs.ReducerName => "JoinLobby";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags JoinLobbyFlags;
    public void JoinLobby(CallReducerFlags flags) => JoinLobbyFlags = flags;
  }
}
