// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void LeaveLobbyHandler(ReducerEventContext ctx, ulong lobbyId);
    public event LeaveLobbyHandler? OnLeaveLobby;

    public void LeaveLobby(ulong lobbyId) {
      conn.InternalCallReducer(new Reducer.LeaveLobby(lobbyId), this.SetCallReducerFlags.LeaveLobbyFlags);
    }

    public bool InvokeLeaveLobby(ReducerEventContext ctx, Reducer.LeaveLobby args) {
      if (OnLeaveLobby == null)
        return false;
      OnLeaveLobby(
          ctx,
          args.LobbyId
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LeaveLobby : Reducer, IReducerArgs {
      [DataMember(Name = "lobbyId")]
      public ulong LobbyId;

      public LeaveLobby(ulong LobbyId) {
        this.LobbyId = LobbyId;
      }

      public LeaveLobby() {
      }

      string IReducerArgs.ReducerName => "LeaveLobby";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags LeaveLobbyFlags;
    public void LeaveLobby(CallReducerFlags flags) => LeaveLobbyFlags = flags;
  }
}
