// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types {
  public sealed partial class RemoteReducers : RemoteBase {
    public delegate void StartLobbyHandler(ReducerEventContext ctx, StartLobbySchedule schedule);
    public event StartLobbyHandler? OnStartLobby;

    public void StartLobby(StartLobbySchedule schedule) {
      conn.InternalCallReducer(new Reducer.StartLobby(schedule), this.SetCallReducerFlags.StartLobbyFlags);
    }

    public bool InvokeStartLobby(ReducerEventContext ctx, Reducer.StartLobby args) {
      if (OnStartLobby == null)
        return false;
      OnStartLobby(
          ctx,
          args.Schedule
      );
      return true;
    }
  }

  public abstract partial class Reducer {
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StartLobby : Reducer, IReducerArgs {
      [DataMember(Name = "schedule")]
      public StartLobbySchedule Schedule;

      public StartLobby(StartLobbySchedule Schedule) {
        this.Schedule = Schedule;
      }

      public StartLobby() {
        this.Schedule = new();
      }

      string IReducerArgs.ReducerName => "StartLobby";
    }
  }

  public sealed partial class SetReducerFlags {
    internal CallReducerFlags StartLobbyFlags;
    public void StartLobby(CallReducerFlags flags) => StartLobbyFlags = flags;
  }
}
